#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
      $OTHER_INSTALLS
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
apt update && apt upgrade -y
apt install git -y
_other_installs

mkdir ./app
chmod 777 ./app
cd /app

apt -qq update && apt -qq install -y git wget pv jq python3-dev mediainfo

apt -qq update --fix-missing && \
apt -qq install -y git \
aria2 \
wget \
curl \
busybox \
unzip \
unrar \
tar \
python3 \
ffmpeg \
python3-pip \
p7zip-full \
p7zip-rar

wget https://rclone.org/install.sh
bash install.sh

mkdir /app/gautam
wget -O /app/gautam/gclone.gz https://git.io/JJMSG
gzip -d /app/gautam/gclone.gz
chmod 0775 /app/gautam/gclone

pip3 install -U pip
git clone $REPO_URL torrentleech-gdrive
cd torrentleech-gdrive
requirements.txt .
pip3 install --no-cache-dir -r requirements.txt
cp -r /app/torrentleech-gdrive/* /app
_externals
bash $PYTHON_FILE
