#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
      $OTHER_INSTALLS
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
apt update && apt upgrade -y
apt install git -y
_other_installs
pip3 install -U pip
git clone $REPO_URL torrentleech-gdrive
cd torrentleech-gdrive
requirements.txt .
pip3 install --no-cache-dir -r requirements.txt
cp -r /app/torrentleech-gdrive/* /app
_externals
bash $PYTHON_FILE
