#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
RUN apt update && apt upgrade -y
RUN apt install git -y

_other_installs

RUN pip3 install -U pip
RUN git clone $REPO_URL mirrorbot/ && cd mirrorbot
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

_externals

CMD ["bash", "$PYTHON_FILE"]
